<?php

namespace Isen\GamePf\Games\GoBundle\Repository;

/**
 * GoGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoGameRepository extends \Doctrine\ORM\EntityRepository
{
}
