<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * WaitingRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaitingRoomRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRoom(String $name, int $modeId){
        $query = $this->createQueryBuilder('r')
            ->where('r.name = :name')
            ->setParameter('name', $name)
            ->andWhere('r.modeId = :id')
            ->setParameter('id', $modeId)
            ->andWhere('r.url IS NULL')
            ->getQuery();
        return $query->setMaxResults(1)->getOneOrNullResult();
    }

}
